# Generated by Django 4.2.14 on 2024-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weather',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Cloudy', 'Cloudy'), ('Snowy', 'Snowy'), ('Any', 'Any')], default='any', max_length=100),
        ),
    ]
